name: Orihost AFK Bot (Hardcoded Cookie)

on:
  schedule:
    - cron: '0 */5 * * *'   # mỗi 5 tiếng (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 300   # 5 tiếng

    env:
      PYTHONUNBUFFERED: 1  # in log realtime

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11 (cache pip)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AFK script
        run: |
          python main.py
